# Generated by Django 3.1.2 on 2020-10-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201028_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Administration'), (2, 'Accounts')], default=0),
        ),
    ]
