# Generated by Django 3.1.2 on 2020-12-04 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201030_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Administration'), (2, 'Accounts')], default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other')], default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
