# Generated by Django 3.1.2 on 2020-11-27 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('paid_by', models.CharField(max_length=40)),
                ('paid_date', models.DateField()),
                ('paid_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_status', models.BooleanField(default=False)),
                ('account_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.accounthead')),
            ],
        ),
    ]
