# Generated by Django 3.1.2 on 2020-12-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_paid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.accounthead'),
        ),
    ]
