# Generated by Django 3.1.4 on 2021-01-11 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20201227_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='division',
            field=models.PositiveSmallIntegerField(choices=[(0, 'GENERAL'), (1, 'COGNITIVE SOLUTIONS'), (2, 'CODELAB SYSTEMS'), (3, 'DATAQUE SYSTEMS')], default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
