# Generated by Django 3.1.2 on 2020-10-22 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0004_auto_20201022_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='PUC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SSLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(default='profile_pic/default.png', null=True, upload_to='profile_pic/')),
                ('address', models.TextField()),
                ('contact_1', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)])),
                ('contact_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gaurdian_name', models.CharField(max_length=40)),
                ('guardian_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)])),
                ('is_whatsapp_contact_1', models.BooleanField(default=False)),
                ('is_whatsapp_contact_2', models.BooleanField(default=False)),
                ('college_register_no', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=40)),
                ('client_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)])),
                ('client_email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('sslc_percentage', models.FloatField()),
                ('puc_percentage', models.FloatField()),
                ('degree_percentage', models.FloatField()),
                ('additional_qualifications', models.TextField()),
                ('extracurricular_activities', models.TextField()),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.backend')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.college')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.course')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree', to='programs.college')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.frontend')),
                ('puc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_projects.puc')),
                ('sslc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_projects.sslc')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.stream')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
