# Generated by Django 3.1.2 on 2020-10-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='register_no',
            field=models.CharField(default='1', editable=False, max_length=8, unique=True),
        ),
    ]
