# Generated by Django 3.1.2 on 2020-10-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0002_studentproject_register_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='register_no',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
