# Generated by Django 3.1.2 on 2020-11-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0007_auto_20201126_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='trainer_1_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_projects.trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentproject',
            name='trainer_1_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_projects.trainerrole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentproject',
            name='trainer_2_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_2', to='student_projects.trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentproject',
            name='trainer_2_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_2_role', to='student_projects.trainerrole'),
            preserve_default=False,
        ),
    ]
