# Generated by Django 3.1.2 on 2020-12-01 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0008_auto_20201126_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='actual_fees',
            field=models.FloatField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentproject',
            name='concession',
            field=models.FloatField(default=500, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentproject',
            name='is_fees_paid',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
