# Generated by Django 3.1.2 on 2020-12-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0009_auto_20201201_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='actual_fees',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='client_contact',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='company',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='frontend',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='title',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='trainer_1_name',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='trainer_1_role',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='trainer_2_name',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='trainer_2_role',
        ),
    ]
