# Generated by Django 3.1.2 on 2020-12-02 20:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_auto_20201127_1419'),
        ('student_projects', '0010_auto_20201202_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=40)),
                ('client_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)])),
                ('client_email', models.EmailField(max_length=254)),
                ('actual_fees', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.backend')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.company')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.frontend')),
                ('trainer_1_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_projects.trainer')),
                ('trainer_1_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_projects.trainerrole')),
                ('trainer_2_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_2', to='student_projects.trainer')),
                ('trainer_2_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_2_role', to='student_projects.trainerrole')),
            ],
        ),
    ]
