# Generated by Django 3.1.2 on 2020-12-04 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0012_studentproject_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='degree_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='puc_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='sslc_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
