# Generated by Django 3.1.4 on 2021-04-07 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0015_auto_20201227_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='actual_fees',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='concession',
        ),
        migrations.AddField(
            model_name='studentproject',
            name='fees',
            field=models.FloatField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
