# Generated by Django 3.1.4 on 2021-04-14 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0016_auto_20210407_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='fees',
        ),
        migrations.AddField(
            model_name='studentproject',
            name='actual_fees',
            field=models.FloatField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentproject',
            name='concession',
            field=models.FloatField(default=400, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
