# Generated by Django 3.1.4 on 2021-04-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0017_auto_20210414_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentproject',
            old_name='degree_backlog',
            new_name='degree_no_of_attempts',
        ),
        migrations.RenameField(
            model_name='studentproject',
            old_name='puc_backlog',
            new_name='puc_no_of_attemps',
        ),
        migrations.RenameField(
            model_name='studentproject',
            old_name='sslc_backlog',
            new_name='sslc_no_of_attempts',
        ),
    ]
