# Generated by Django 3.1.2 on 2020-10-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0010_auto_20201027_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CognitiveInternshipFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('purpose', models.PositiveSmallIntegerField(choices=[(1, 'REGISTRATION'), (2, 'INTERNSHIP')])),
                ('amount', models.PositiveIntegerField()),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.paymenttype')),
                ('recieved_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.cognitiveinternship')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
