# Generated by Django 3.1.2 on 2020-10-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20201028_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicinternshipfees',
            old_name='recieved_from',
            new_name='received_from',
        ),
        migrations.RenameField(
            model_name='cognitiveinternshipfees',
            old_name='recieved_from',
            new_name='received_from',
        ),
        migrations.RenameField(
            model_name='employeeinternshipfees',
            old_name='recieved_from',
            new_name='received_from',
        ),
    ]
