# Generated by Django 3.1.2 on 2020-11-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_auto_20201110_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinternshipfees',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cognitiveinternshipfees',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employeeinternshipfees',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
