# Generated by Django 3.1.2 on 2020-12-01 12:56

import accounts.all.fees.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0009_auto_20201201_1256'),
        ('fees', '0007_academicworkshopfees_cognitiveworkshopfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProjectFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.paymenttype')),
                ('received_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_projects.studentproject')),
            ],
            options={
                'abstract': False,
            },
            bases=(accounts.all.fees.models.StudentProjectFeesCleanMixin, models.Model),
        ),
    ]
