# Generated by Django 3.1.2 on 2020-12-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0015_auto_20201227_1240'),
        ('programs', '0026_auto_20201227_1235'),
        ('fees', '0009_auto_20201204_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinternshipfees',
            name='mode_of_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.paymenttype'),
        ),
        migrations.AlterField(
            model_name='academicinternshipfees',
            name='received_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.academicinternship'),
        ),
        migrations.AlterField(
            model_name='academicworkshopfees',
            name='mode_of_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.paymenttype'),
        ),
        migrations.AlterField(
            model_name='academicworkshopfees',
            name='received_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.academicworkshop'),
        ),
        migrations.AlterField(
            model_name='cognitiveinternshipfees',
            name='mode_of_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.paymenttype'),
        ),
        migrations.AlterField(
            model_name='cognitiveinternshipfees',
            name='received_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ci_fees', to='programs.cognitiveinternship'),
        ),
        migrations.AlterField(
            model_name='cognitiveworkshopfees',
            name='mode_of_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.paymenttype'),
        ),
        migrations.AlterField(
            model_name='cognitiveworkshopfees',
            name='received_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.cognitiveworkshop'),
        ),
        migrations.AlterField(
            model_name='employeeinternshipfees',
            name='mode_of_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.paymenttype'),
        ),
        migrations.AlterField(
            model_name='employeeinternshipfees',
            name='received_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.employeeinternship'),
        ),
        migrations.AlterField(
            model_name='studentprojectfees',
            name='mode_of_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.paymenttype'),
        ),
        migrations.AlterField(
            model_name='studentprojectfees',
            name='received_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_projects.studentproject'),
        ),
    ]
