# Generated by Django 3.1.2 on 2020-12-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_auto_20201227_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinternshipfees',
            name='amount_in_words',
            field=models.TextField(default='Ten Thousand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicworkshopfees',
            name='amount_in_words',
            field=models.TextField(default='Ten Thousand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cognitiveinternshipfees',
            name='amount_in_words',
            field=models.TextField(default='Ten Thousand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cognitiveworkshopfees',
            name='amount_in_words',
            field=models.TextField(default='Ten Thousand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeinternshipfees',
            name='amount_in_words',
            field=models.TextField(default='Ten Thousand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprojectfees',
            name='amount_in_words',
            field=models.TextField(default='Ten Thousand'),
            preserve_default=False,
        ),
    ]
