# Generated by Django 3.1.4 on 2021-03-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0028_batch_status'),
        ('fees', '0011_auto_20201227_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicworkshopfees',
            name='received_from',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.academicworkshop'),
        ),
        migrations.AlterField(
            model_name='cognitiveworkshopfees',
            name='received_from',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.cognitiveworkshop'),
        ),
    ]
