# Generated by Django 3.1.4 on 2021-04-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0012_auto_20210317_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinternshipfees',
            name='amount_in_words',
        ),
        migrations.RemoveField(
            model_name='academicworkshopfees',
            name='amount_in_words',
        ),
        migrations.RemoveField(
            model_name='cognitiveinternshipfees',
            name='amount_in_words',
        ),
        migrations.RemoveField(
            model_name='cognitiveworkshopfees',
            name='amount_in_words',
        ),
        migrations.RemoveField(
            model_name='employeeinternshipfees',
            name='amount_in_words',
        ),
        migrations.RemoveField(
            model_name='studentprojectfees',
            name='amount_in_words',
        ),
    ]
