# Generated by Django 3.1.2 on 2020-10-17 13:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('max_sem', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(default='profile_pic/default.png', null=True, upload_to='profile_pic/')),
                ('address', models.TextField()),
                ('contact_1', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('contact_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gaurdian_name', models.CharField(max_length=40)),
                ('guardian_contact', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('role', models.CharField(max_length=20)),
                ('register_no', models.CharField(editable=False, max_length=8, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('actual_fees', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('concession', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_admission', models.DateField(auto_now_add=True)),
                ('no_of_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.backend')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.company')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.frontend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CognitiveWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(default='profile_pic/default.png', null=True, upload_to='profile_pic/')),
                ('address', models.TextField()),
                ('contact_1', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('contact_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gaurdian_name', models.CharField(max_length=40)),
                ('guardian_contact', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('semester', models.PositiveSmallIntegerField()),
                ('register_no', models.CharField(editable=False, max_length=8, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('actual_fees', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('concession', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_workshop', models.DateField()),
                ('no_of_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('no_of_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.backend')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.course')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.frontend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CognitiveInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(default='profile_pic/default.png', null=True, upload_to='profile_pic/')),
                ('address', models.TextField()),
                ('contact_1', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('contact_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gaurdian_name', models.CharField(max_length=40)),
                ('guardian_contact', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('semester', models.PositiveSmallIntegerField()),
                ('register_no', models.CharField(editable=False, max_length=8, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('actual_fees', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('concession', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_admission', models.DateField(auto_now_add=True)),
                ('no_of_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.backend')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.course')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.frontend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(default='profile_pic/default.png', null=True, upload_to='profile_pic/')),
                ('address', models.TextField()),
                ('contact_1', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('contact_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gaurdian_name', models.CharField(max_length=40)),
                ('guardian_contact', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('semester', models.PositiveSmallIntegerField()),
                ('register_no', models.CharField(editable=False, max_length=8, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('actual_fees', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('concession', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_workshop', models.DateField()),
                ('no_of_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('no_of_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.backend')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.course')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.frontend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(default='profile_pic/default.png', null=True, upload_to='profile_pic/')),
                ('address', models.TextField()),
                ('contact_1', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('contact_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gaurdian_name', models.CharField(max_length=40)),
                ('guardian_contact', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)])),
                ('semester', models.PositiveSmallIntegerField()),
                ('register_no', models.CharField(editable=False, max_length=8, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('actual_fees', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('concession', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_admission', models.DateField(auto_now_add=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.backend')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.course')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.frontend')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
