# Generated by Django 3.1.2 on 2020-10-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20201027_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitiveinternship',
            name='previous_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.course'),
            preserve_default=False,
        ),
    ]
