# Generated by Django 3.1.2 on 2020-10-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20201027_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicinternship',
            old_name='gaurdian_name',
            new_name='guardian_name',
        ),
        migrations.RenameField(
            model_name='cognitiveinternship',
            old_name='gaurdian_name',
            new_name='guardian_name',
        ),
        migrations.RenameField(
            model_name='employeeinternship',
            old_name='gaurdian_name',
            new_name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='academicworkshop',
            name='gaurdian_name',
        ),
        migrations.RemoveField(
            model_name='cognitiveworkshop',
            name='gaurdian_name',
        ),
    ]
