# Generated by Django 3.1.2 on 2020-11-10 21:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_auto_20201028_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicworkshop',
            name='actual_fees',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicworkshop',
            name='backend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.backend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicworkshop',
            name='frontend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.frontend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cognitiveworkshop',
            name='actual_fees',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cognitiveworkshop',
            name='backend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.backend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cognitiveworkshop',
            name='frontend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.frontend'),
            preserve_default=False,
        ),
    ]
