# Generated by Django 3.1.2 on 2020-11-27 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_auto_20201110_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_workshop', models.DateField()),
                ('no_of_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('no_of_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('technology', models.TextField()),
                ('actual_fees', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='academicworkshop',
            name='actual_fees',
        ),
        migrations.RemoveField(
            model_name='academicworkshop',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='academicworkshop',
            name='date_of_workshop',
        ),
        migrations.RemoveField(
            model_name='academicworkshop',
            name='frontend',
        ),
        migrations.RemoveField(
            model_name='academicworkshop',
            name='no_of_days',
        ),
        migrations.RemoveField(
            model_name='academicworkshop',
            name='no_of_hours',
        ),
        migrations.RemoveField(
            model_name='cognitiveworkshop',
            name='actual_fees',
        ),
        migrations.RemoveField(
            model_name='cognitiveworkshop',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='cognitiveworkshop',
            name='date_of_workshop',
        ),
        migrations.RemoveField(
            model_name='cognitiveworkshop',
            name='frontend',
        ),
        migrations.RemoveField(
            model_name='cognitiveworkshop',
            name='no_of_days',
        ),
        migrations.RemoveField(
            model_name='cognitiveworkshop',
            name='no_of_hours',
        ),
    ]
