# Generated by Django 3.1.2 on 2020-11-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_auto_20201127_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicworkshop',
            name='workshop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.workshop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cognitiveworkshop',
            name='workshop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.workshop'),
            preserve_default=False,
        ),
    ]
