# Generated by Django 3.1.2 on 2020-11-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_auto_20201127_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinternship',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='academicinternship',
            name='to_time',
        ),
        migrations.RemoveField(
            model_name='academicworkshop',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='academicworkshop',
            name='to_time',
        ),
        migrations.RemoveField(
            model_name='cognitiveinternship',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='cognitiveinternship',
            name='to_time',
        ),
        migrations.RemoveField(
            model_name='cognitiveworkshop',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='cognitiveworkshop',
            name='to_time',
        ),
        migrations.RemoveField(
            model_name='employeeinternship',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='employeeinternship',
            name='to_time',
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.internship')),
            ],
        ),
    ]
