# Generated by Django 3.1.2 on 2020-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_auto_20201204_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinternship',
            name='backlog',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicinternship',
            name='overall_percentage',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
