# Generated by Django 3.1.2 on 2020-12-27 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0024_auto_20201204_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='start_date',
        ),
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
