# Generated by Django 3.1.2 on 2020-12-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0025_auto_20201227_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinternship',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.batch'),
        ),
        migrations.AlterField(
            model_name='academicinternship',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.college'),
        ),
        migrations.AlterField(
            model_name='academicinternship',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.course'),
        ),
        migrations.AlterField(
            model_name='academicworkshop',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.college'),
        ),
        migrations.AlterField(
            model_name='academicworkshop',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.course'),
        ),
        migrations.AlterField(
            model_name='academicworkshop',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.workshop'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='internship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.internship'),
        ),
        migrations.AlterField(
            model_name='cognitiveinternship',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.batch'),
        ),
        migrations.AlterField(
            model_name='cognitiveinternship',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.college'),
        ),
        migrations.AlterField(
            model_name='cognitiveinternship',
            name='previous_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.course'),
        ),
        migrations.AlterField(
            model_name='cognitiveworkshop',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.college'),
        ),
        migrations.AlterField(
            model_name='cognitiveworkshop',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.course'),
        ),
        migrations.AlterField(
            model_name='cognitiveworkshop',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.workshop'),
        ),
        migrations.AlterField(
            model_name='employeeinternship',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.batch'),
        ),
        migrations.AlterField(
            model_name='employeeinternship',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.company'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='backend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.backend'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='frontend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.frontend'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.course'),
        ),
    ]
