# Generated by Django 3.1.2 on 2020-12-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0026_auto_20201227_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
